name: Resize Wallpapers

on:
  push:

jobs:
  resize-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pillow
      run: pip install pillow

    - name: Resize images
      run: |
        python3 <<EOF
        import os
        from PIL import Image

        input_folder = 'originals'
        sizes = {
          'phone': (1080, 1920),
          'desktop': (1920, 1080)
        }

        for filename in os.listdir(input_folder):
            if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
                img_path = os.path.join(input_folder, filename)
                img = Image.open(img_path)

                for label, size in sizes.items():
                    img_copy = img.copy()
                    img_copy.thumbnail(size, Image.LANCZOS)

                    output_folder = label
                    if not os.path.exists(output_folder):
                        os.makedirs(output_folder)

                    base, ext = os.path.splitext(filename)
                    new_filename = f"{base}-{label}{ext}"
                    save_path = os.path.join(output_folder, new_filename)
                    img_copy.save(save_path)
                    print(f"Saved {new_filename} to {output_folder}")
        EOF

    - name: Commit and push resized images
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add phone desktop
        git commit -m "Add resized wallpapers for phone and desktop" || echo "No changes to commit"
        git push
